/**
 * Created by kodanda_rama on 5/23/17.
 */
export const REQUEST_SHOW_STORIES_IDS = "REQUEST_SHOW_STORIES_IDS";
export const RECEIVE_SHOW_STORIES_IDS = "RECEIVE_SHOW_STORIES_IDS";
export const REQUEST_SHOW_STORIES_IDS_FAILED = "REQUEST_SHOW_STORIES_IDS_FAILED";

export const REQUEST_SHOW_STORIES = "REQUEST_SHOW_STORIES";
export const RECEIVE_SHOW_STORIES = "RECEIVE_SHOW_STORIES";
export const REQUEST_SHOW_STORIES_FAILED = "REQUEST_SHOW_STORIES_FAILED";