/**
 * Created by kodanda_rama on 5/23/17.
 */
export const REQUEST_USER_PROFILE = "REQUEST_USER_PROFILE";
export const RECEIVE_USER_PROFILE = "RECEIVE_USER_PROFILE";
export const REQUEST_USER_PROFILE_FAILED = "REQUEST_USER_PROFILE_FAILED";

export const RESET_USER_PROFILE = "RESET_USER_PROFILE";