/**
 * Created by kodanda_rama on 5/26/17.
 */
export const REQUEST_STORY = "REQUEST_STORY";
export const RECEIVE_STORY = "RECEIVE_STORY";
export const REQUEST_STORY_FAILED = "REQUEST_STORY_FAILED";

export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const REQUEST_COMMENTS_FAILED = "REQUEST_COMMENTS_FAILED";

export const RESET_STORY_DESCRIPTION = "RESET_STORY_DESCRIPTION";