/**
 * Created by kodanda_rama on 5/23/17.
 */
export const REQUEST_BEST_STORIES_IDS = "REQUEST_BEST_STORIES_IDS";
export const RECEIVE_BEST_STORIES_IDS = "RECEIVE_BEST_STORIES_IDS";
export const REQUEST_BEST_STORIES_IDS_FAILED = "REQUEST_BEST_STORIES_IDS_FAILED";

export const REQUEST_BEST_STORIES = "REQUEST_BEST_STORIES";
export const RECEIVE_BEST_STORIES = "RECEIVE_BEST_STORIES";
export const REQUEST_BEST_STORIES_FAILED = "REQUEST_BEST_STORIES_FAILED";