/**
 * Created by kodanda_rama on 5/23/17.
 */
export const REQUEST_TOP_STORIES_IDS = "REQUEST_TOP_STORIES_IDS";
export const RECEIVE_TOP_STORIES_IDS = "RECEIVE_TOP_STORIES_IDS";
export const REQUEST_TOP_STORIES_IDS_FAILED = "REQUEST_TOP_STORIES_IDS_FAILED";

export const REQUEST_TOP_STORIES = "REQUEST_TOP_STORIES";
export const RECEIVE_TOP_STORIES = "RECEIVE_TOP_STORIES";
export const REQUEST_TOP_STORIES_FAILED = "REQUEST_TOP_STORIES_FAILED";