/**
 * Created by kodanda_rama on 5/23/17.
 */
export const REQUEST_ASK_STORIES_IDS = "REQUEST_ASK_STORIES_IDS";
export const RECEIVE_ASK_STORIES_IDS = "RECEIVE_ASK_STORIES_IDS";
export const REQUEST_ASK_STORIES_IDS_FAILED = "REQUEST_ASK_STORIES_IDS_FAILED";

export const REQUEST_ASK_STORIES = "REQUEST_ASK_STORIES";
export const RECEIVE_ASK_STORIES = "RECEIVE_ASK_STORIES";
export const REQUEST_ASK_STORIES_FAILED = "REQUEST_ASK_STORIES_FAILED";