/**
 * Created by kodanda_rama on 5/23/17.
 */
export const REQUEST_NEW_STORIES_IDS = "REQUEST_NEW_STORIES_IDS";
export const RECEIVE_NEW_STORIES_IDS = "RECEIVE_NEW_STORIES_IDS";
export const REQUEST_NEW_STORIES_IDS_FAILED = "REQUEST_NEW_STORIES_IDS_FAILED";

export const REQUEST_NEW_STORIES = "REQUEST_NEW_STORIES";
export const RECEIVE_NEW_STORIES = "RECEIVE_NEW_STORIES";
export const REQUEST_NEW_STORIES_FAILED = "REQUEST_NEW_STORIES_FAILED";